import { Stack } from 'expo-router';

/**
 * Production navigation - the 9 approved routes from
 * ProjectDocs/01-information-architecture.md. The Figma prototype bottom
 * navigation is NOT part of production navigation.
 *
 * Screen names must match the actual route names generated by the file
 * layout: a directory with only an `index` route resolves to the directory
 * name, while a dynamic route keeps its `[param]` segment.
 */
export default function RootLayout() {
  return (
    <Stack screenOptions={{ headerShown: false }}>
      <Stack.Screen name="(index)" />
      <Stack.Screen name="nickname" />
      <Stack.Screen name="create-room" />
      <Stack.Screen name="join-room" />
      <Stack.Screen name="lobby/[roomId]" />
      <Stack.Screen name="game/[roomId]" />
      <Stack.Screen name="round-result/[roomId]" />
      <Stack.Screen name="final-result/[roomId]" />
      <Stack.Screen name="settings" />
    </Stack>
  );
}
